### ISSUE TITLE
WakeOnLAN video audio volume appears much lower than the average YouTube video audio volume

### ISSUE THREAD

**Issue by pzaino** [RISC-OS-Community/WakeOnLAN#11]
# Background

@mattharris ,
quick thought, today I have compared the audio volume of your video with the average youtube videos audio-volume. 
It seems that WakeOnLAN video audio-volume is way lower than the audio-volume of the average youtube video. 

Could you please check and, if I am correct, apply some audio compression to increase the base volume of your video? Please compare with general YouTube video.

Why is this a potential problem? Because if indeed the volume of the video is too low compared to the average video audio-volume and advertisements and a user is forced to increase his computer volume, then, when an ad may start or when the video switch for another one we may cause the user to have an heart attack ;)

Thanks.

**Comment by mattharris** [comment]
@pzaino Yes, you are right - I'd forgotten to properly post-process the audio before uploading - at the time I was more interested if the preferred version was with or without audio and rushed the publication prior to doing the last steps.

I've generated a new version where I've applied make-up gain, along with some compression.

However, this will need to be uploaded as a new video, complete with new URL, as YouTube does not permit changing an existing video.

So, we've got two options once the new video is uploaded:

1. Unpublish/delete the original version thereby loosing the current stats.
2. Keep both, but update the description and add a pinned comment pointing to the new version.

Which option do you think we should go for?

**Comment by mattharris** [comment]
New version is now uploaded here: https://youtu.be/DITiZoxlEBg

It's unlisted right now - if you confirm that this is better, then I'll make it public.

**Comment by pzaino** [comment]
@mattharris ,
looks and sound perfect, I did again the test of watching it between two regular youtube videos.

Really a great job! :)

**Comment by pzaino** [comment]
publishing the latest update now on the riscpkg repository, so we can spread the news on the "media"! :)

just let me know when the new video is ready, thx

**Comment by mattharris** [comment]
I've made the new version public. Also updated the description and title of the original one to point to the new one.

For now the old one is still there - will probably de-list it in the future.

**Comment by mattharris** [comment]
PR #12 updates the README link to point at the new version.

**Comment by pzaino** [comment]
Thanks, merged and checked, everything looks good! :)

**Comment by mattharris** [comment]
As an FYI I've just now de-listed the original video that had the lower audio level. I _think_ that it was causing some confusion as it was possibly still being recommended to people.
