### ISSUE TITLE
MAC address is not saved

### ISSUE THREAD

**Issue by mattharris** [RISC-OS-Community/WakeOnLAN#6]
# Background

When choosing 'Save Options' in the UI, the IP Broadcast Addr is saved, but not the Target MAC Addr.

# Questions
- Is this intentional behaviour?
- Would it not make more sense to also save the MAC address?
- If this is intended, what is the rationale? (Just trying to understand intended use case)

**Comment by pzaino** [comment]
Ok, tested latest updates straight from the packman repo and MAC is now been saved when the user saves the options. I guess we can close this issue :)

In case it's needed we can open it again, thanks.
